// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ProjetoOdontologico.Repositorio.Migrations
{
    [DbContext(typeof(ProjetoOdontologicoContexto))]
    partial class ProjetoOdontologicoContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AgendamentoID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("Ativo");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataHora");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("Descricao");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("PacienteID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Status");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioID");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Agendamentos", (string)null);
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.ContaReceber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ContaReceberID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("Ativo");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataVencimento");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("PacienteID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Status");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioID");

                    b.Property<decimal>("ValorReceber")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ValorReceber");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ContasReceber", (string)null);
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.Especialidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("EspecialidadeId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("Ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nome");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Especialidades", (string)null);
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("FormaPagamentoID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("Ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("NomeForma");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("FormasPagamento", (string)null);
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.MovimentacaoFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MovimentacaoFinanceiraID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("Ativo");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataMovimentacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Descricao");

                    b.Property<int>("FormaPagamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("FormaPagamentoID");

                    b.Property<string>("TipoMovimento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("TipoMovimento");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioID");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimentacoesFinanceiras", (string)null);
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("OrcamentoID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("Ativo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataCriacao");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("PacienteID");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Total");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioID");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Orcamentos", (string)null);
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.OrcamentoProcedimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("OrcamentoProcedimentoID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("Ativo");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Descricao");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("OrcamentoID");

                    b.Property<int>("ProcedimentoId")
                        .HasColumnType("integer")
                        .HasColumnName("ProcedimentoID");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoId");

                    b.HasIndex("ProcedimentoId");

                    b.ToTable("OrcamentoProcedimentos", (string)null);
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PacienteID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("Ativo");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("CPF");

                    b.Property<DateTime?>("DataNascimento")
                        .IsRequired()
                        .HasColumnType("DATE")
                        .HasColumnName("DataNascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Endereco");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Genero");

                    b.Property<string>("HistoricoMedico")
                        .HasColumnType("TEXT")
                        .HasColumnName("HistoricoMedico");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Telefone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.Procedimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ProcedimentoID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("Descricao");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("EspecialidadeID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nome");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioId");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Procedimentos", (string)null);
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("Ativo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Senha");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.Agendamento", b =>
                {
                    b.HasOne("ProjetoOdontologico.Dominio.Entidades.Paciente", "Paciente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjetoOdontologico.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Agendamentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.ContaReceber", b =>
                {
                    b.HasOne("ProjetoOdontologico.Dominio.Entidades.Paciente", "Paciente")
                        .WithMany("ContasReceber")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjetoOdontologico.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("ContasReceber")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.Especialidade", b =>
                {
                    b.HasOne("ProjetoOdontologico.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Especialidades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.FormaPagamento", b =>
                {
                    b.HasOne("ProjetoOdontologico.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("FormasPagamento")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.MovimentacaoFinanceira", b =>
                {
                    b.HasOne("ProjetoOdontologico.Dominio.Entidades.FormaPagamento", "FormaPagamento")
                        .WithMany("MovimentacoesFinanceiras")
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjetoOdontologico.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("MovimentacoesFinanceiras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FormaPagamento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.Orcamento", b =>
                {
                    b.HasOne("ProjetoOdontologico.Dominio.Entidades.Paciente", "Paciente")
                        .WithMany("Orcamentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjetoOdontologico.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Orcamentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.OrcamentoProcedimento", b =>
                {
                    b.HasOne("ProjetoOdontologico.Dominio.Entidades.Orcamento", "Orcamento")
                        .WithMany("OrcamentosProcedimentos")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjetoOdontologico.Dominio.Entidades.Procedimento", "Procedimento")
                        .WithMany("OrcamentosProcedimentos")
                        .HasForeignKey("ProcedimentoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Orcamento");

                    b.Navigation("Procedimento");
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.Paciente", b =>
                {
                    b.HasOne("ProjetoOdontologico.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Pacientes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.Procedimento", b =>
                {
                    b.HasOne("ProjetoOdontologico.Dominio.Entidades.Especialidade", "Especialidade")
                        .WithMany("Procedimentos")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjetoOdontologico.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Procedimentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Especialidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.Especialidade", b =>
                {
                    b.Navigation("Procedimentos");
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.FormaPagamento", b =>
                {
                    b.Navigation("MovimentacoesFinanceiras");
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.Orcamento", b =>
                {
                    b.Navigation("OrcamentosProcedimentos");
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.Paciente", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("ContasReceber");

                    b.Navigation("Orcamentos");
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.Procedimento", b =>
                {
                    b.Navigation("OrcamentosProcedimentos");
                });

            modelBuilder.Entity("ProjetoOdontologico.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("ContasReceber");

                    b.Navigation("Especialidades");

                    b.Navigation("FormasPagamento");

                    b.Navigation("MovimentacoesFinanceiras");

                    b.Navigation("Orcamentos");

                    b.Navigation("Pacientes");

                    b.Navigation("Procedimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
